### ISSUE TITLE
Maximum propagators exceeded

### ISSUE THREAD

**Issue by AllenZzw** [huub-solver/huub#130]
When solving the [p_7_SGSG_GSG_yumi_grid_setup_5_5_zones.dzn](https://github.com/MiniZinc/minizinc.github.io/blob/main/public/challenge/2021/mznc2021_probs/yumi-dynamic/data/p_7_SGSG_GSG_yumi_grid_setup_5_5_zones.dzn) instance with [the model](https://github.com/MiniZinc/minizinc.github.io/blob/main/public/challenge/2021/mznc2021_probs/yumi-dynamic/yumi-dynamic.mzn), the solver will output the following message: 
>thread 'main' panicked at crates/huub/src/solver/engine/activation_list.rs:68:9:
Unable to add more than u16::MAX propagators to the activation list of a single variable.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Dekker1** [comment]
It does seem like the instance is legitimately creating and attaching more than 65,536 propagators to the same variable. It seems likely that implementing the `diffn` or `circuit` global will resolve this issue, but I'm not 100% sure.

We could increase the maximum number of attached propagators, but I'm just not sure how our solver would do anything with the number of variables/propagators used in this instance currently.

```
%%%mzn-stat: flatBoolVars=378893
%%%mzn-stat: flatIntVars=639692
%%%mzn-stat: flatBoolConstraints=133400
%%%mzn-stat: flatIntConstraints=897424
```

I think we should probably wait to further investigate this issue until we have some more global constraint propagators.

P.S. You do indeed need the version from the 2024 challenge to compile using the current version of MiniZinc.

**Comment by Dekker1** [comment]
I had some discussions with Guido, who also thought that 16 bits was not enough. The increase to 32 bit indexes is only 64 bits per variable, so let's just go for it.
