### ISSUE TITLE
[Feature] Support all basic MiniZinc constraints

### ISSUE THREAD

**Issue by Dekker1** [huub-solver/huub#20]
One of the initial goals in the project is to support all basic MiniZinc constraints. We are currently working from the following lists.

**Required Constraints**

- [x] `array_bool_and`
- [x] `array_bool_element`
- [x] `array_bool_xor`
- [x] `array_int_element`
- [x] `array_var_bool_element`
- [x] `array_var_int_element`
- [x] `bool2int`
- [x] `bool_clause`
- [x] `bool_clause_reif`
- [x] `bool_eq_reif`
- [x] `bool_lin_eq`
- [x] `bool_lt`
- [x] `bool_lt_reif`
- [x] `bool_not`
- [x] `bool_xor`
- [x] `int_abs` (can be decomposed)
- [x] `int_div` (can be decomposed)
- [x] `int_eq_reif`
- [x] `int_le`
- [x] `int_le_reif`
- [x] `int_lin_eq`
- [x] `int_lin_eq_reif`
- [x] `int_lin_le`
- [x] `int_lin_le_reif`
- [x] `int_lin_ne`
- [x] `int_lin_ne_reif`
- [x] `int_max`
- [x] `int_min`
- [x] `int_mod` (can be decomposed)
- [x] `int_ne_reif`
- [x] `int_pow`
- [x] `int_times` (Peter mentioned https://dl.acm.org/doi/pdf/10.1145/1065887.1065889 as a description for simple bounds propagator)
- [x] `set_in`
- [x] `set_in_reif`

**Optional Constraints**

- [x] `all_different`
- [x] `array_int_maximum`
- [x] `array_int_minimum`

**Comment by Dekker1** [comment]
Support for `int_lin_le` and `int_lin_eq` was added in https://github.com/Dekker1/huub/pull/17

**Comment by AllenZzw** [comment]
Support for `int_max` and `int_min` was added in https://github.com/Dekker1/huub/pull/18

**Comment by Dekker1** [comment]
Support for final basic constraint was added in https://github.com/Dekker1/huub/pull/47
