### ISSUE TITLE
No reason for a literal in 1UIP analysis

### ISSUE THREAD

**Issue by AllenZzw** [huub-solver/huub#82]
The instance is from MiniZinc challenge 2015. 
[nmseq.fzn.json](https://github.com/user-attachments/files/16633366/nmseq.fzn.json)

The error message is as follows: 

> fzn-huub: vendor/cadical/src/shrink.cpp:234: unsigned int CaDiCaL::Internal::shrink_along_reason(int, int, bool, bool&, unsigned int): Assertion `v.reason' failed.

This complains that the reason for a literal involved in 1UIP analysis is wanted, but the reason is null.

**Comment by AllenZzw** [comment]
Resolved in #125

**Comment by Dekker1** [comment]
Is this actually resolved, or now just hidden to when restarts are enabled? #125 changed the default restarting behaviour to be disabled. Does it occur when you use the ‘--restart on’ flag?

**Comment by AllenZzw** [comment]
> Is this actually resolved, or now just hidden to when restarts are enabled? #125 changed the default restarting behaviour to be disabled. Does it occur when you use the ‘--restart on’ flag?

Thanks for the reminder! I did try using ‘--restart true’ and '--vivify true' flag, and no error occur. It seems like the issue has been resolved.
